#!/bin/bash

# Copyright 2015 Philipp Winter <phw@nymity.ch>
#
# This file is part of herbivore.
#
# exitmap is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# exitmap is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with exitmap.  If not, see <http://www.gnu.org/licenses/>.

script_dir=$(dirname "$0")
load_config="${script_dir}/load_config.sh"

source "$load_config"

if [ "$#" -lt 1 ]
then
    echo
    echo "Usage: $0 NUM_NEWEST_CONSENSUSES"
    echo
    exit 1
fi

num="$1"

# Now that we know where the consensus archives are, find most recent n
# consensuses.

if [ -z "$Consensuses" ]
then
    echo "Variable 'Consensuses' is unset.  Is it not set in 'config.cfg?'"
    exit 1
fi
mkdir -p "$Consensuses"
find "$Consensuses" -type f | sort | tail -"$num"
